(function(root,factory){
  const api=factory();
  if(root) root.GuitarDiaryI18n=api;
  if(typeof module==='object'&&module.exports) module.exports=api;
})(typeof window!=='undefined'?window:typeof globalThis!=='undefined'?globalThis:null,function(){
  const LANGUAGE_KEY='rifflog-language-v1';
  const translations={
    ru:{
      appTitle:'Гитара с Прокопием — дневник занятий',brandMain:'Гитара',brandWith:'с Прокопием',brandSubtitle:'дневник занятий',navJournal:'Мой дневник',navStats:'Прогресс',navMaterials:'Материалы',navWords:'Слова',navChords:'Аккорды',tipTitle:'Маленький шаг каждый день',tipText:'10 минут сегодня лучше, чем час когда-нибудь.',profileCabinet:'Личный кабинет',languageLabel:'🌐 Язык интерфейса',languageRussian:'Русский',languageEnglish:'English',
      openNavigation:'Открыть навигацию',closeNavigation:'Закрыть навигацию',openProgress:'Открыть мой прогресс',openProfile:'Открыть личный кабинет',previousMonth:'Предыдущий месяц',nextMonth:'Следующий месяц',close:'Закрыть',decreaseFont:'Уменьшить шрифт',increaseFont:'Увеличить шрифт',songFontSize:'Размер текста песни',
      greeting:'Привет, ',streakCurrent:'ТЕКУЩАЯ СЕРИЯ',streakNote:'Серия считает только дни, когда ты заходил в дневник.',day:'день',daysFew:'дня',days:'дней',rhythmEyebrow:'ТВОЙ РИТМ',rhythmTitle:'Всё под контролем',teacher:'💬 Преподавателю',today:'Сегодня',monthSessions:'Занятий в этом месяце',weekTime:'Время за неделю',goal:'Цель:',editGoal:'Изменить цель',previousMonthChange:'к прошлому месяцу',minutes:'мин',insightLabel:'ИНСАЙТ ДНЯ',insightNone:'На сегодня инсайта нет — добавь мысль после занятия.',addInsight:'Добавить инсайт',edit:'Редактировать',delete:'Удалить',allInsights:'Все инсайты',calendarCaption:'Нажми на день, чтобы открыть запись',calendarFrom:'Занятия с {date}',hasEntry:'Есть запись',selectedDay:'Выбранный день',beforeStart:'До старта',dateToday:'Сегодня, {date}',dateWeekday:'{weekday}, {date}',noPeriod:'Нет периода',chartPercent:'{value}%',chartMinutes:'{value} мин',streakSuffix:' подряд',openTelegramProfile:'Открыть профиль Telegram {username}',
      diary:'ДНЕВНИК',newEntry:'НОВАЯ ЗАПИСЬ',savedEntry:'ЗАПИСЬ СОХРАНЕНА',training:'Тренировка сегодня',trainingHint:'Что делал на занятии',trainingPlaceholder:'Например: разучивал бой, тренировался под метроном...',homework:'Домашнее задание',homeworkHint:'Можно писать в свободной форме',homeworkPlaceholder:'Например: гамма Ля минор, 3 подхода по 5 минут...',lessonTime:'Время занятия',minutesLong:'минут',myProgress:'Мой прогресс',started:'Начал',almostReady:'Почти готово',done:'Сделано',completed:'Отметить как выполненное',saveEntry:'Сохранить запись',previewEmpty:'Нажми, чтобы добавить задание',open:'Открыть',
      recentEyebrow:'ПОСЛЕДНИЕ ЗАПИСИ',recentTitle:'Твои занятия',showAll:'Показать все',localData:'Данные хранятся на этом устройстве',downloadBackup:'Скачать копию',restoreBackup:'Восстановить',recentEmpty:'Пока нет записей — добавь первое занятие в календаре.',noDescription:'Без описания',time:'Время:',recentResult:'Результат:',
      progressEyebrow:'ПРОГРЕСС',progressTitle:'Ритм складывается из дней',progressDescription:'Каждая точка — твой прогресс в конкретный день после даты старта.',backDiary:'← В дневник',averageProgress:'Средняя результативность',practiceDays:'Дней с занятиями',thisMonth:'за текущий месяц',progressChartEyebrow:'ПРОГРЕСС ПО ДНЯМ',progressChartTitle:'Прогресс занятия',progressChartAria:'График прогресса занятия по дням',chartEmpty:'Добавь первую запись в дневнике — здесь появится график.',progressLegend:'Прогресс занятия',yPercent:'Ось Y: проценты',timeChartEyebrow:'ВРЕМЯ ПО ДНЯМ',timeChartTitle:'Время занятий',timeChartAria:'График времени занятий по дням',timeLegend:'Время занятия',yMinutes:'Ось Y: минуты',weightedByTime:'с учётом времени занятий',
      materialsEyebrow:'МАТЕРИАЛЫ ДЛЯ СЕБЯ',materialsTitle:'Инсайты и избранное',materialsDescription:'Сохраняй важные мысли и информацию для следующих занятий.',addInsightButton:'＋ Добавить инсайт',addFavoriteButton:'☆ Добавить избранное',favoritesEyebrow:'ИЗБРАННОЕ',favoritesTitle:'Важная информация',favoritesDescription:'Открой тему, чтобы прочитать сохранённую заметку.',favoriteSearch:'Поиск в избранном...',favoritesEmpty:'Избранное пока пусто.',favoritesEmptyHint:'Сохрани первую важную информацию, чтобы быстро находить её на занятиях.',nothingFound:'Ничего не найдено.',favoriteSearchHint:'Попробуй изменить запрос или очистить поиск.',favoriteOpenHint:'Нажми, чтобы открыть информацию',favoriteOpenAria:'Открыть тему «{title}»',updated:'Обновлено {date}',insightsEyebrow:'ИНСАЙТЫ ПО ДНЯМ',observations:'Твои наблюдения',insightsDescription:'Каждая мысль привязана к выбранной дате.',insightsEmpty:'Пока нет инсайтов. Добавь первую мысль для себя.',insightDay:'ИНСАЙТ ДНЯ',
      wordsEyebrow:'СЛОВА И ТЕСТ',wordsTitle:'Термины для гитариста',wordsDescription:'Собирай свою библиотеку и проверяй, что уже запомнилось.',modeAria:'Режим тренировки',libraryTab:'📚 Библиотека',testTab:'🧠 Тест',statsTab:'📊 Статистика',myLibrary:'МОЯ БИБЛИОТЕКА',addTerm:'Добавить термин',editTerm:'Редактировать термин',word:'Слово / термин',wordHint:'Например, arpeggio',meaning:'Значение',meaningHint:'Коротко и понятно',category:'Категория',optional:'Необязательно',categoryPlaceholder:'Например, техника',technique:'Техника',theory:'Теория',musicTerms:'Музыкальные термины',notes:'Ноты',chords:'Аккорды',other:'Другое',cancel:'Отмена',add:'Добавить',save:'Сохранить',studentWords:'СЛОВА УЧЕНИКА',termsTitle:'Твои термины',termSearch:'Поиск термина или значения...',termSearchAria:'Поиск термина или значения',allTerms:'Все термины',wordsEmpty:'Твоя библиотека пока пуста.',wordsEmptyHint:'Добавь первый музыкальный термин, чтобы начать обучение.',categoryEmpty:'В этой категории пока нет слов',categoryEmptyHint:'Пройди термин в тесте, чтобы его статус обновился.',searchEmpty:'Ничего не найдено',searchEmptyHint:'Попробуй изменить запрос поиска.',errorsToday:'Ошибок сегодня: {count}',
      quizReady:'ГОТОВ К ТРЕНИРОВКЕ?',quizTitle:'Проверь свои знания',quizDescription:'Выбери количество слов и напиши значение своими словами.',wordsAvailable:'Доступно слов:',allWords:'Все слова',fiveWords:'5 слов',tenWords:'10 слов',difficultWords:'Сложные слова',startTest:'Начать тест',quizEmpty:'Добавь хотя бы один термин, чтобы начать тест.',question:'Вопрос',questionMeaning:'ЧТО ОЗНАЧАЕТ ЭТОТ ТЕРМИН?',yourMeaning:'Твоё значение',answerHint:'Ответ своими словами',answerPlaceholder:'Введите значение...',check:'Проверить',correct:'✅ Правильно!',incorrect:'❌ Пока не совсем. Правильное значение: {meaning}',selfCorrect:'Я ответил верно',selfCorrectDone:'✅ Засчитано как верный ответ!',nextWord:'Следующее слово',practiceComplete:'ТРЕНИРОВКА ЗАКОНЧЕНА',testComplete:'Тест завершён',correctAnswers:'Правильных ответов:',result:'Результат',correctStreak:'🔥 Правильных подряд:',reviewedTerms:'📚 Повторено терминов:',errors:'❌ Ошибок:',repeatErrors:'🔁 Повторить ошибки',tryAgain:'Пройти ещё раз',backLibrary:'Вернуться в библиотеку',noDifficult:'Сложных слов пока нет',noErrors:'В этом тесте не было ошибок',noCategoryWords:'В этой категории пока нет слов',writeAnswer:'Напиши свой вариант ответа',
      statusNew:'🔴 Не знаю',statusLearning:'🟡 Изучаю',statusKnown:'🟢 Знаю',statusMastered:'⭐ Закреплено',dailyKnown:'🟢 Знаю сегодня',dailyLearning:'🟡 Изучаю сегодня',dailyDifficult:'🔴 Сложные сегодня',wordsProgress:'ПРОГРЕСС',mastered:'Освоено',of:'из',todayUpper:'СЕГОДНЯ',dailyActivity:'Дневная активность',reviewed:'Повторено терминов',correctShort:'Правильных',accuracy:'Точность',currentMonth:'ТЕКУЩИЙ МЕСЯЦ',dailyTotal:'Итог по дням',totalTests:'Всего тестов',totalAnswers:'Всего ответов',averageAccuracy:'Средняя точность',allTime:'ЗА ВСЁ ВРЕМЯ',results:'Результаты',totalTerms:'📚 Всего терминов',knownToday:'🟢 Знаю сегодня',learningToday:'🟡 Изучаю сегодня',difficultToday:'🔴 Сложные сегодня',
      songsEyebrow:'МОИ ПЕСНИ',songsTitle:'Песни и аккорды',songsDescription:'Сохраняй тексты любимых песен и держи аккорды прямо над ними.',songLibrary:'БИБЛИОТЕКА ПЕСЕН',addSong:'Добавить песню',editSong:'Редактировать песню',songTitle:'Название песни',songTitleHint:"Например, Knockin' on Heaven's Door",songTitlePlaceholder:'Название песни',artist:'Исполнитель',artistPlaceholder:'Исполнитель или автор',chordsAbove:'Аккорды над текстом',chordsHint:'Например, Am · F · C · G',chordsPlaceholder:'Am        F        C        G',chordsHintText:'Можно записать несколько строк аккордов — они будут показаны сверху.',lyrics:'Текст песни',lyricsHint:'Переносы строк сохранятся',lyricsPlaceholder:'Вставь сюда текст песни...',savedSongs:'Сохранённые песни',songSearch:'Поиск по названию, автору или тексту...',songSearchAria:'Поиск песни',songsEmpty:'Библиотека песен пока пуста.',songsEmptyHint:'Добавь первую песню, чтобы открыть её в любой момент.',songsNotFound:'Песни не найдены.',songsNotFoundHint:'Попробуй изменить запрос поиска.',songOpenHint:'Открыть текст и аккорды',songOpenAria:'Открыть песню «{title}»',allSongs:'← Все песни',fontSize:'Размер текста',song:'ПЕСНЯ',chordsDisplay:'АККОРДЫ',lyricsDisplay:'ТЕКСТ ПЕСНИ',mySong:'Моя песня',
      profileEyebrow:'ЛИЧНЫЙ КАБИНЕТ',profileTitle:'Твои данные',profileDescription:'Имя и дата старта сохраняются только на этом устройстве.',studentProfile:'Профиль ученика',studentHint:'Настрой календарь под свой путь',yourName:'Твоё имя',nameHint:'Будет в приветствии',namePlaceholder:'Например, Максим',startDate:'Дата начала занятий',startDateHint:'С неё начинается календарь',startDateHelp:'Дни до выбранной даты будут отмечены в календаре как недоступные для записей.',saveProfile:'Сохранить профиль',messageTeacher:'💬 Написать преподавателю',newProfile:'Новый профиль',newProfileHint:'Очистит записи и начнёт отсчёт с сегодняшней даты.',startOver:'Начать заново',defaultName:'Максим',initialFallback:'У',
      newInsight:'Новый инсайт',editInsight:'Редактировать инсайт',insightDate:'День инсайта',anyDate:'Можно выбрать любую дату',insightText:'Текст инсайта',required:'Поле обязательно',insightPlaceholder:'Например: расслабленная кисть звучит свободнее...',insightHint:'Инсайт сохранится только для выбранной даты.',saveInsight:'Сохранить инсайт',newInformation:'Новая информация',editInformation:'Редактировать информацию',topicName:'Название темы',topicHint:'Например, Аппликатуры аккордов',topicPlaceholder:'Название важной информации',importantInformation:'Важная информация',detailedHint:'Можно писать подробно',favoritePlaceholder:'Внеси сюда информацию, к которой захочешь вернуться...',favoriteDetail:'Важная информация',weeklyGoalEyebrow:'НЕДЕЛЬНАЯ ЦЕЛЬ',weeklyGoal:'Изменить цель',minutesPerWeek:'Минут в неделю',minutesPerWeekHint:'Например, 180',weeklyGoalHint:'Цель сохранится на этом устройстве и обновит обе шкалы прогресса.',saveGoal:'Сохранить цель',
      dayBeforeStart:'Этот день был до начала занятий',entryDeleted:'Запись удалена',favoriteDeleted:'Избранное удалено',insightDeleted:'Инсайт удалён',songDeleted:'Песня удалена',termDeleted:'Термин удалён',entrySaved:'Запись сохранена',weeklyGoalInvalid:'Цель должна быть не меньше 1 минуты',weeklyGoalUpdated:'Цель недели обновлена',songRequired:'Заполни название, аккорды и текст',songUpdated:'Песня обновлена',songAdded:'Песня добавлена',termRequired:'Заполни слово и значение',termUpdated:'Термин изменён',termAdded:'Термин добавлен',insightDateRequired:'Выбери дату инсайта',insightRequired:'Поле инсайта обязательно',insightSaved:'Инсайт сохранён',favoriteRequired:'Заполни название и информацию',favoriteUpdated:'Избранное обновлено',favoriteAdded:'Информация добавлена в избранное',profileRequired:'Заполни имя и дату начала',profileSaved:'Профиль сохранён',profileCreated:'Новый профиль создан',noEntry:'В этот день ещё нет записи',entryRequired:'Добавь тренировку, задание или время занятия',startDateRequired:'Выбери день начиная с даты старта',answerRequired:'Напиши свой вариант ответа',backupSent:'Резервная копия отправлена',backupDownloaded:'Резервная копия скачана',backupExportFailed:'Не удалось создать резервную копию',jsonOnly:'Выбери JSON-файл',backupRestored:'Данные успешно восстановлены',backupEmpty:'Файл резервной копии пуст.',backupJson:'Не удалось прочитать JSON-файл.',backupRoot:'Файл имеет неверный формат.',backupApp:'Это не резервная копия Guitar Diary.',backupVersion:'Версия резервной копии не поддерживается.',backupData:'В резервной копии отсутствуют данные.',backupStructure:'Структура резервной копии повреждена.',fileRead:'Не удалось прочитать файл.',fileAborted:'Чтение файла отменено.',storage:'Не удалось сохранить данные. Текущие данные могли остаться без изменений.',backupGeneric:'Не удалось восстановить резервную копию.',deleteEntryConfirm:'Удалить запись за {date}?',deleteFavoriteConfirm:'Удалить тему «{title}»?',deleteInsightConfirm:'Удалить инсайт за {date}?',deleteSongConfirm:'Удалить песню «{title}»?',deleteTermConfirm:'Удалить термин «{word}»?',newProfileConfirm:'Начать новый профиль? Все записи занятий на этом устройстве будут удалены.',restoreConfirm:'Текущие данные будут заменены данными из резервной копии. Продолжить?'
    },
    en:{
      appTitle:'Guitar with Prokopiy — practice diary',brandMain:'Guitar',brandWith:'with Prokopiy',brandSubtitle:'practice diary',navJournal:'My diary',navStats:'Progress',navMaterials:'Materials',navWords:'Words',navChords:'Chords',tipTitle:'A small step every day',tipText:'10 minutes today is better than an hour someday.',profileCabinet:'Profile',languageLabel:'🌐 Interface language',languageRussian:'Русский',languageEnglish:'English',
      openNavigation:'Open navigation',closeNavigation:'Close navigation',openProgress:'Open my progress',openProfile:'Open profile',previousMonth:'Previous month',nextMonth:'Next month',close:'Close',decreaseFont:'Decrease font size',increaseFont:'Increase font size',songFontSize:'Song text size',
      greeting:'Hello, ',streakCurrent:'CURRENT STREAK',streakNote:'Your streak counts only the days when you visit the diary.',day:'day',daysFew:'days',days:'days',rhythmEyebrow:'YOUR RHYTHM',rhythmTitle:'Everything under control',teacher:'💬 Message teacher',today:'Today',monthSessions:'Sessions this month',weekTime:'Time this week',goal:'Goal:',editGoal:'Edit goal',previousMonthChange:'from last month',minutes:'min',insightLabel:'DAILY INSIGHT',insightNone:'No insight for today yet — add a thought after practice.',addInsight:'Add insight',edit:'Edit',delete:'Delete',allInsights:'All insights',calendarCaption:'Tap a day to open its entry',calendarFrom:'Practice from {date}',hasEntry:'Has entry',selectedDay:'Selected day',beforeStart:'Before start',dateToday:'Today, {date}',dateWeekday:'{weekday}, {date}',noPeriod:'No period',chartPercent:'{value}%',chartMinutes:'{value} min',streakSuffix:'',openTelegramProfile:'Open Telegram profile {username}',
      diary:'DIARY',newEntry:'NEW ENTRY',savedEntry:'ENTRY SAVED',training:'Practice today',trainingHint:'What did you practice?',trainingPlaceholder:'For example: practiced strumming, trained with a metronome...',homework:'Homework',homeworkHint:'Write freely',homeworkPlaceholder:'For example: A minor scale, 3 rounds of 5 minutes...',lessonTime:'Practice time',minutesLong:'minutes',myProgress:'My progress',started:'Started',almostReady:'Almost ready',done:'Done',completed:'Mark as complete',saveEntry:'Save entry',previewEmpty:'Tap to add homework',open:'Open',
      recentEyebrow:'RECENT ENTRIES',recentTitle:'Your practice',showAll:'Show all',localData:'Data is stored on this device',downloadBackup:'Download backup',restoreBackup:'Restore',recentEmpty:'No entries yet — add your first practice in the calendar.',noDescription:'No description',time:'Time:',recentResult:'Result:',
      progressEyebrow:'PROGRESS',progressTitle:'Your rhythm is built day by day',progressDescription:'Each point shows your progress on a specific day after the start date.',backDiary:'← To diary',averageProgress:'Average progress',practiceDays:'Practice days',thisMonth:'this month',progressChartEyebrow:'PROGRESS BY DAY',progressChartTitle:'Practice progress',progressChartAria:'Practice progress chart by day',chartEmpty:'Add your first diary entry to see the chart here.',progressLegend:'Practice progress',yPercent:'Y-axis: percent',timeChartEyebrow:'TIME BY DAY',timeChartTitle:'Practice time',timeChartAria:'Practice time chart by day',timeLegend:'Practice time',yMinutes:'Y-axis: minutes',weightedByTime:'weighted by practice time',
      materialsEyebrow:'MATERIALS FOR YOU',materialsTitle:'Insights and favorites',materialsDescription:'Save important thoughts and information for future practice.',addInsightButton:'＋ Add insight',addFavoriteButton:'☆ Add favorite',favoritesEyebrow:'FAVORITES',favoritesTitle:'Important information',favoritesDescription:'Open a topic to read the saved note.',favoriteSearch:'Search favorites...',favoritesEmpty:'Favorites are empty for now.',favoritesEmptyHint:'Save your first important note to find it quickly during practice.',nothingFound:'Nothing found.',favoriteSearchHint:'Try changing your search or clearing it.',favoriteOpenHint:'Tap to open information',favoriteOpenAria:'Open topic “{title}”',updated:'Updated {date}',insightsEyebrow:'DAILY INSIGHTS',observations:'Your observations',insightsDescription:'Each thought is linked to the selected date.',insightsEmpty:'No insights yet. Add your first thought.',insightDay:'DAILY INSIGHT',
      wordsEyebrow:'WORDS AND TEST',wordsTitle:'Terms for guitarists',wordsDescription:'Build your library and check what you remember.',modeAria:'Practice mode',libraryTab:'📚 Library',testTab:'🧠 Test',statsTab:'📊 Statistics',myLibrary:'MY LIBRARY',addTerm:'Add term',editTerm:'Edit term',word:'Word / term',wordHint:'For example, arpeggio',meaning:'Meaning',meaningHint:'Short and clear',category:'Category',optional:'Optional',categoryPlaceholder:'For example, technique',technique:'Technique',theory:'Theory',musicTerms:'Music terms',notes:'Notes',chords:'Chords',other:'Other',cancel:'Cancel',add:'Add',save:'Save',studentWords:'STUDENT WORDS',termsTitle:'Your terms',termSearch:'Search term or meaning...',termSearchAria:'Search term or meaning',allTerms:'All terms',wordsEmpty:'Your library is empty for now.',wordsEmptyHint:'Add your first musical term to start learning.',categoryEmpty:'No words in this category yet',categoryEmptyHint:'Practice a term in the test to update its status.',searchEmpty:'Nothing found',searchEmptyHint:'Try changing your search.',errorsToday:'Errors today: {count}',
      quizReady:'READY TO PRACTICE?',quizTitle:'Test your knowledge',quizDescription:'Choose how many words to review and write the meaning in your own words.',wordsAvailable:'Words available:',allWords:'All words',fiveWords:'5 words',tenWords:'10 words',difficultWords:'Difficult words',startTest:'Start test',quizEmpty:'Add at least one term to start the test.',question:'Question',questionMeaning:'WHAT DOES THIS TERM MEAN?',yourMeaning:'Your meaning',answerHint:'Answer in your own words',answerPlaceholder:'Enter the meaning...',check:'Check',correct:'✅ Correct!',incorrect:'❌ Not quite. Correct meaning: {meaning}',selfCorrect:'I got it right',selfCorrectDone:'✅ Counted as a correct answer!',nextWord:'Next word',practiceComplete:'PRACTICE COMPLETE',testComplete:'Test complete',correctAnswers:'Correct answers:',result:'Result',correctStreak:'🔥 Correct in a row:',reviewedTerms:'📚 Terms reviewed:',errors:'❌ Errors:',repeatErrors:'🔁 Repeat errors',tryAgain:'Try again',backLibrary:'Back to library',noDifficult:'No difficult words yet',noErrors:'There were no errors in this test',noCategoryWords:'No words in this category yet',writeAnswer:'Write your answer',
      statusNew:'🔴 New',statusLearning:'🟡 Learning',statusKnown:'🟢 Known',statusMastered:'⭐ Mastered',dailyKnown:'🟢 Known today',dailyLearning:'🟡 Learning today',dailyDifficult:'🔴 Difficult today',wordsProgress:'PROGRESS',mastered:'Mastered',of:'of',todayUpper:'TODAY',dailyActivity:'Daily activity',reviewed:'Terms reviewed',correctShort:'Correct',accuracy:'Accuracy',currentMonth:'CURRENT MONTH',dailyTotal:'Daily total',totalTests:'Total tests',totalAnswers:'Total answers',averageAccuracy:'Average accuracy',allTime:'ALL TIME',results:'Results',totalTerms:'📚 Total terms',knownToday:'🟢 Known today',learningToday:'🟡 Learning today',difficultToday:'🔴 Difficult today',
      songsEyebrow:'MY SONGS',songsTitle:'Songs and chords',songsDescription:'Save your favorite lyrics and keep the chords right above them.',songLibrary:'SONG LIBRARY',addSong:'Add song',editSong:'Edit song',songTitle:'Song title',songTitleHint:"For example, Knockin' on Heaven's Door",songTitlePlaceholder:'Song title',artist:'Artist',artistPlaceholder:'Artist or author',chordsAbove:'Chords above lyrics',chordsHint:'For example, Am · F · C · G',chordsPlaceholder:'Am        F        C        G',chordsHintText:'You can add several chord lines — they will be shown above.',lyrics:'Lyrics',lyricsHint:'Line breaks will be preserved',lyricsPlaceholder:'Paste the lyrics here...',savedSongs:'Saved songs',songSearch:'Search by title, artist, or lyrics...',songSearchAria:'Search songs',songsEmpty:'Your song library is empty for now.',songsEmptyHint:'Add your first song to open it anytime.',songsNotFound:'No songs found.',songsNotFoundHint:'Try changing your search.',songOpenHint:'Open lyrics and chords',songOpenAria:'Open song “{title}”',allSongs:'← All songs',fontSize:'Text size',song:'SONG',chordsDisplay:'CHORDS',lyricsDisplay:'LYRICS',mySong:'My song',
      profileEyebrow:'PROFILE',profileTitle:'Your details',profileDescription:'Your name and start date are saved only on this device.',studentProfile:'Student profile',studentHint:'Set up the calendar for your journey',yourName:'Your name',nameHint:'Shown in the greeting',namePlaceholder:'For example, Alex',startDate:'Practice start date',startDateHint:'The calendar starts here',startDateHelp:'Days before this date will be unavailable for entries.',saveProfile:'Save profile',messageTeacher:'💬 Message teacher',newProfile:'New profile',newProfileHint:'Clears entries and starts counting from today.',startOver:'Start over',defaultName:'Alex',initialFallback:'S',
      newInsight:'New insight',editInsight:'Edit insight',insightDate:'Insight day',anyDate:'Any date can be selected',insightText:'Insight text',required:'Required field',insightPlaceholder:'For example: a relaxed wrist sounds freer...',insightHint:'The insight is saved only for the selected date.',saveInsight:'Save insight',newInformation:'New information',editInformation:'Edit information',topicName:'Topic name',topicHint:'For example, Chord shapes',topicPlaceholder:'Name this important information',importantInformation:'Important information',detailedHint:'You can write in detail',favoritePlaceholder:'Add information you will want to revisit...',favoriteDetail:'Important information',weeklyGoalEyebrow:'WEEKLY GOAL',weeklyGoal:'Edit goal',minutesPerWeek:'Minutes per week',minutesPerWeekHint:'For example, 180',weeklyGoalHint:'This goal is saved on this device and updates both progress bars.',saveGoal:'Save goal',
      dayBeforeStart:'This day is before your practice start',entryDeleted:'Entry deleted',favoriteDeleted:'Favorite deleted',insightDeleted:'Insight deleted',songDeleted:'Song deleted',termDeleted:'Term deleted',entrySaved:'Entry saved',weeklyGoalInvalid:'The goal must be at least 1 minute',weeklyGoalUpdated:'Weekly goal updated',songRequired:'Fill in the title, chords, and lyrics',songUpdated:'Song updated',songAdded:'Song added',termRequired:'Fill in the word and meaning',termUpdated:'Term updated',termAdded:'Term added',insightDateRequired:'Choose an insight date',insightRequired:'Insight text is required',insightSaved:'Insight saved',favoriteRequired:'Fill in the title and information',favoriteUpdated:'Favorite updated',favoriteAdded:'Information added to favorites',profileRequired:'Fill in your name and start date',profileSaved:'Profile saved',profileCreated:'New profile created',noEntry:'There is no entry for this day yet',entryRequired:'Add practice, homework, or practice time',startDateRequired:'Choose a day from the practice start date onward',answerRequired:'Write your answer',backupTitle:'Guitar Diary backup',backupSent:'Backup shared',backupDownloaded:'Backup downloaded',backupExportFailed:'Could not create a backup',jsonOnly:'Choose a JSON file',backupRestored:'Data restored successfully',backupEmpty:'The backup file is empty.',backupJson:'Could not read the JSON file.',backupRoot:'The file has an invalid format.',backupApp:'This is not a Guitar Diary backup.',backupVersion:'This backup version is not supported.',backupData:'The backup has no data field.',backupStructure:'The backup structure is corrupted.',fileRead:'Could not read the file.',fileAborted:'File reading was cancelled.',storage:'Could not save the data. Current data may be unchanged.',backupGeneric:'Could not restore the backup.',deleteEntryConfirm:'Delete the entry for {date}?',deleteFavoriteConfirm:'Delete topic “{title}”?',deleteInsightConfirm:'Delete the insight for {date}?',deleteSongConfirm:'Delete song “{title}”?',deleteTermConfirm:'Delete term “{word}”?',newProfileConfirm:'Start a new profile? All practice entries on this device will be deleted.',restoreConfirm:'Current data will be replaced with the backup data. Continue?'
    }
  };
  Object.assign(translations.ru,{daysFew:'дня',recentResult:'Результат:',dateToday:'Сегодня, {date}',dateWeekday:'{weekday}, {date}',noPeriod:'Нет периода',chartPercent:'{value}%',chartMinutes:'{value} мин',streakSuffix:' подряд',openTelegramProfile:'Открыть профиль Telegram {username}',backupTitle:'Резервная копия Guitar Diary',saveSong:'Сохранить песню',newStudent:'Новый ученик',mainNavigation:'Основная навигация',mobileNavigation:'Мобильная навигация',greetingPrefix:'Привет,',quizYourself:'Проверь себя',quizDescriptionFull:'Напиши значение термина своими словами. Варианты ответа не подсказываются.',inLibrary:'В библиотеке',difficultWaiting:'сложных слов ждут повторения',newWords:'Новые',reviewWords:'На повторение',difficultFilter:'Сложные',whatReview:'ЧТО БУДЕМ ПОВТОРЯТЬ?',randomOrder:'Порядок будет случайным',quantity:'КОЛИЧЕСТВО',lessWords:'Если слов меньше — возьмём все',wholeLibrary:'Вся библиотека',shortPractice:'Короткая тренировка',mediumPractice:'Средняя тренировка',twentyWords:'20 слов',fullPractice:'Полная тренировка',quizEmptyTitle:'Библиотека пока пуста',quizEmptyText:'Добавь первые термины, чтобы начать тренировку.',termCountLabel:'терминов',quizMissedHeading:'Стоит повторить:',statsLabel:'Статистика',wordPlaceholder:'arpeggio',meaningPlaceholder:'перебор струн',languageEyebrow:'ЯЗЫК',weekdaySun:'ВС',weekdayMon:'ПН',weekdayTue:'ВТ',weekdayWed:'СР',weekdayThu:'ЧТ',weekdayFri:'ПТ',weekdaySat:'СБ'});
  Object.assign(translations.en,{daysFew:'days',recentResult:'Result:',dateToday:'Today, {date}',dateWeekday:'{weekday}, {date}',noPeriod:'No period',chartPercent:'{value}%',chartMinutes:'{value} min',streakSuffix:'',openTelegramProfile:'Open Telegram profile {username}',saveSong:'Save song',newStudent:'New student',mainNavigation:'Main navigation',mobileNavigation:'Mobile navigation',greetingPrefix:'Hello,',quizYourself:'Test yourself',quizDescriptionFull:'Write the term meaning in your own words. No answer choices are shown.',inLibrary:'In the library',difficultWaiting:'difficult words are waiting for review',newWords:'New',reviewWords:'Review',difficultFilter:'Difficult',whatReview:'WHAT SHALL WE REVIEW?',randomOrder:'The order will be random',quantity:'NUMBER OF WORDS',lessWords:'If there are fewer words, we will use them all',wholeLibrary:'Full library',shortPractice:'Short practice',mediumPractice:'Medium practice',twentyWords:'20 words',fullPractice:'Full practice',quizEmptyTitle:'The library is empty',quizEmptyText:'Add your first terms to start practicing.',termCountLabel:'terms',quizMissedHeading:'Worth reviewing:',statsLabel:'Statistics',wordPlaceholder:'arpeggio',meaningPlaceholder:'string picking',languageEyebrow:'LANGUAGE',weekdaySun:'SU',weekdayMon:'MO',weekdayTue:'TU',weekdayWed:'WE',weekdayThu:'TH',weekdayFri:'FR',weekdaySat:'SA'});
  Object.assign(translations.ru,{downloadBackupButton:'↓ Скачать копию',restoreBackupButton:'↑ Восстановить'});
  Object.assign(translations.en,{downloadBackupButton:'↓ Download backup',restoreBackupButton:'↑ Restore'});
  Object.assign(translations.ru,{languageGroupAria:'Язык интерфейса'});
  Object.assign(translations.en,{languageGroupAria:'Interface language'});
  Object.assign(translations.ru,{goalLower:'цель:',weekdaySun:'ВС',weekdayMon:'ПН',weekdayTue:'ВТ',weekdayWed:'СР',weekdayThu:'ЧТ',weekdayFri:'ПТ',weekdaySat:'СБ'});
  Object.assign(translations.en,{goalLower:'goal:',weekdaySun:'SU',weekdayMon:'MO',weekdayTue:'TU',weekdayWed:'WE',weekdayThu:'TH',weekdayFri:'FR',weekdaySat:'SA'});
  Object.assign(translations.ru,{teacherSession:'Занятие с педагогом'});
  Object.assign(translations.en,{teacherSession:'Lesson with teacher'});
  const dateLabels={ru:{months:['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],monthsGen:['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'],weekdaysLong:['ВОСКРЕСЕНЬЕ','ПОНЕДЕЛЬНИК','ВТОРНИК','СРЕДА','ЧЕТВЕРГ','ПЯТНИЦА','СУББОТА'],weekdays:['вс','пн','вт','ср','чт','пт','сб']},en:{months:['January','February','March','April','May','June','July','August','September','October','November','December'],monthsGen:['January','February','March','April','May','June','July','August','September','October','November','December'],weekdaysLong:['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'],weekdays:['Su','Mo','Tu','We','Th','Fr','Sa']}};
  function normalizeLanguage(value){ return value==='ru'||value==='en'?value:null; }
  function detectLanguage(systemLanguage){ const value=String(systemLanguage===undefined?(typeof navigator!=='undefined'?navigator.language:''):systemLanguage).toLowerCase(); return value.startsWith('ru')?'ru':'en'; }
  function loadLanguage(storage,systemLanguage){ let stored=null; try{ stored=storage?.getItem?.(LANGUAGE_KEY); }catch(error){} return normalizeLanguage(stored)||detectLanguage(systemLanguage); }
  let currentLanguage=loadLanguage(typeof localStorage!=='undefined'?localStorage:null);
  function t(key,values={}){ const template=translations[currentLanguage]?.[key]??translations.en[key]??key; return template.replace(/\{(\w+)\}/g,(_,name)=>values[name]===undefined?'':String(values[name])); }
  function formatDate(date,includeYear=false){ return new Intl.DateTimeFormat(currentLanguage==='ru'?'ru-RU':'en-US',{day:'numeric',month:'long',...(includeYear?{year:'numeric'}:{})}).format(date); }
  function getDateLabels(){ return dateLabels[currentLanguage]; }
  function getLanguage(){ return currentLanguage; }
  function setLanguage(value,persist=true){ const next=normalizeLanguage(value); if(!next) return currentLanguage; const changed=currentLanguage!==next; currentLanguage=next; if(persist&&typeof localStorage!=='undefined'){ try{ localStorage.setItem(LANGUAGE_KEY,currentLanguage); }catch(error){} } if(changed&&typeof window!=='undefined'){ const event=typeof CustomEvent==='function'?new CustomEvent('guitar-diary-language-change',{detail:{language:currentLanguage}}):new Event('guitar-diary-language-change'); window.dispatchEvent(event); } return currentLanguage; }
  const skipSelector='#greeting-name,#top-telegram-link,#profile-telegram-link,#insight-day,#mobile-entry-preview-text,#recent-list,#favorites-list,#insight-list,#songs-list,#terms-list,#streak-days,#quiz-word,#quiz-feedback,#quiz-missed-list,#song-detail-title,#song-detail-artist,#song-detail-chords,#song-detail-lyrics,#favorite-detail-title,#favorite-detail-content,#toast';
  function applyStaticTranslations(){
    if(typeof document==='undefined') return;
    document.documentElement.lang=currentLanguage; document.title=t('appTitle');
    const sourceToKey=new Map(); Object.keys(translations.ru).forEach(key=>{ sourceToKey.set(translations.ru[key],key); sourceToKey.set(translations.en[key],key); });
    const walker=document.createTreeWalker(document.body,4); let node;
    while(node=walker.nextNode()){ if(node.parentElement?.closest(skipSelector)) continue; const value=node.nodeValue.trim(), key=value?sourceToKey.get(value):null; if(key) node.nodeValue=node.nodeValue.replace(value,t(key)); }
    document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(element=>['placeholder','aria-label','title'].forEach(attribute=>{ const value=element.getAttribute(attribute), key=sourceToKey.get(value); if(key) element.setAttribute(attribute,t(key)); }));
    document.querySelectorAll('option').forEach(option=>{ const key=sourceToKey.get(option.value)||sourceToKey.get(option.textContent.trim()); if(key){ option.value=t(key); option.textContent=t(key); } });
    document.querySelectorAll('[data-language-option]').forEach(button=>{ const active=button.dataset.languageOption===currentLanguage; button.classList.toggle('active',active); button.setAttribute('aria-pressed',String(active)); });
  }
  return {LANGUAGE_KEY,translations,normalizeLanguage,detectLanguage,loadLanguage,t,formatDate,getDateLabels,getLanguage,setLanguage,applyStaticTranslations};
});
